launch-dev-backend.sh, launch-dev-docker.sh
Parempi ethernet device matching toteutettu
=> Docker start script updated

src/main/java/fi/minedu/oiva/backend/service/CacheService.java, src/main/java/fi/minedu/oiva/backend/service/EsitysmalliService.java, src/main/java/fi/minedu/oiva/backend/service/ExportService.java, src/main/java/fi/minedu/oiva/backend/service/KohdeService.java, src/main/java/fi/minedu/oiva/backend/service/KoodistoService.java, src/main/java/fi/minedu/oiva/backend/service/LupaService.java, src/main/java/fi/minedu/oiva/backend/service/OrganisaatioService.java, src/main/java/fi/minedu/oiva/backend/task/BuildCaches.java, src/main/java/fi/minedu/oiva/backend/util/RequestUtils.java, src/main/java/fi/minedu/oiva/backend/web/controller/AuthController.java, src/main/java/fi/minedu/oiva/backend/web/controller/CacheController.java, src/main/java/fi/minedu/oiva/backend/web/controller/ExportController.java, src/main/java/fi/minedu/oiva/backend/web/controller/KoodistoController.java, src/main/java/fi/minedu/oiva/backend/web/controller/LupaController.java, src/main/java/fi/minedu/oiva/backend/web/controller/OrganisaatioController.java, src/main/resources/config/application.yml, src/main/scala/fi/minedu/oiva/backend/entity/Kohde.scala, src/main/scala/fi/minedu/oiva/backend/entity/Lupa.scala, src/main/scala/fi/minedu/oiva/backend/entity/Maarays.scala, src/main/scala/fi/minedu/oiva/backend/entity/export/KoulutusLupa.scala, src/main/scala/fi/minedu/oiva/backend/entity/export/Koulutustarjonta.scala, src/main/scala/fi/minedu/oiva/backend/entity/opintopolku/Organisaatio.scala, src/main/scala/fi/minedu/oiva/backend/service/OpintopolkuService.scala
Järjestäjä-tiedot välimuistitetaan
=> Rajapintoja toteutettu

src/main/java/fi/minedu/oiva/backend/config/WebSecurityConfig.java, src/main/java/fi/minedu/oiva/backend/service/AsiatyyppiService.java, src/main/java/fi/minedu/oiva/backend/service/ImportService.java, src/main/java/fi/minedu/oiva/backend/service/KohdeService.java, src/main/java/fi/minedu/oiva/backend/service/LupaService.java, src/main/java/fi/minedu/oiva/backend/service/LupatilaService.java, src/main/java/fi/minedu/oiva/backend/service/MaaraysService.java, src/main/java/fi/minedu/oiva/backend/service/MaaraystyyppiService.java, src/main/java/fi/minedu/oiva/backend/service/PaatoskierrosService.java, src/main/java/fi/minedu/oiva/backend/web/controller/ImportController.java
Proof-of-concept import Lupa and Maaraykset from Lupa json
=> Import Kuja Lupa POC implemented

src/main/java/fi/minedu/oiva/backend/web/controller/PrinceXMLController.java
Poistettu testidataan liittyvät metodit
=> CSCOIVA-483: KJ:n näkymä, hakemuksen esikatselu oikealla datalla

src/main/java/fi/minedu/oiva/backend/config/FileStorageConfig.java, src/main/java/fi/minedu/oiva/backend/service/FileStorageService.java, src/main/resources/config/application.yml
=> Feature filestorage paths

src/main/java/fi/minedu/oiva/backend/security/annotations/OivaAccess.java, src/main/java/fi/minedu/oiva/backend/web/controller/PrinceXMLController.java, src/main/java/fi/minedu/oiva/backend/web/controller/SupportController.java, src/main/scala/fi/minedu/oiva/backend/entity/opintopolku/KayttajaKayttooikeus.scala
Admin roolin viittaus korjattu
=> Admin role fixed

amos-backend/pom.xml, amos-backend/src/main/java/fi/minedu/oiva/backend/service/ExportService.java, amos-backend/src/main/java/fi/minedu/oiva/backend/service/LupaService.java, amos-backend/src/main/java/fi/minedu/oiva/backend/service/MaaraysService.java, amos-backend/src/main/java/fi/minedu/oiva/backend/web/controller/ExportController.java
- Optimized MaaraysService.toMaaraysList method.
- Added spring-dev-tools depencency for quicker development.
=> CSCOIVA-626 Added cost information export api.

amos-backend/src/main/java/fi/minedu/oiva/backend/service/LupaService.java, amos-backend/src/main/java/fi/minedu/oiva/backend/web/controller/LupaController.java, amos-backend/src/test/java/fi/minedu/oiva/backend/web/controller/LupaControllerIT.java, amos-backend/src/test/resources/sql/lupa_data.sql
- LupaController.getAllWithJarjestaja does not return lupa when asiatyyppi is 'PERUUTETTU'.
=> CSCOIVA-638 Added asiatyyppi filter

oiva-core/src/main/scala/fi/minedu/oiva/backend/entity/opintopolku/Koodisto.scala, oiva-core/src/main/scala/fi/minedu/oiva/backend/entity/opintopolku/KoodistoKoodi.scala, oiva-core/src/main/scala/fi/minedu/oiva/backend/entity/opintopolku/Metadata.scala
=> Cscoiva 676: Metadataan lisäyksiä

amos-backend/src/main/java/fi/minedu/oiva/backend/service/FileStorageService.java, amos-backend/src/main/java/fi/minedu/oiva/backend/service/MuutospyyntoService.java, amos-backend/src/main/java/fi/minedu/oiva/backend/service/PebbleService.java, amos-backend/src/main/java/fi/minedu/oiva/backend/template/extension/MuutosListFilter.java, amos-backend/src/main/java/fi/minedu/oiva/backend/web/controller/PebbleController.java, amos-backend/src/main/java/fi/minedu/oiva/backend/web/controller/PrinceXMLController.java, amos-model/src/main/scala/fi/minedu/oiva/backend/entity/oiva/Muutos.scala, amos-model/src/main/scala/fi/minedu/oiva/backend/entity/oiva/Muutospyynto.scala, oiva-core/src/main/scala/fi/minedu/oiva/backend/entity/opintopolku/Organisaatio.scala, oiva-core/src/main/scala/fi/minedu/oiva/backend/service/OpintopolkuService.scala
- Added kasite muutos filter for pebble.
=> CSCOIVA-515 Added muutospyynto pdf preview from db.

amos-backend/src/main/java/fi/minedu/oiva/backend/service/LiiteService.java, amos-backend/src/main/java/fi/minedu/oiva/backend/service/MuutospyyntoService.java, amos-backend/src/main/java/fi/minedu/oiva/backend/web/controller/LiiteController.java, amos-backend/src/main/java/fi/minedu/oiva/backend/web/controller/MuutospyyntoController.java
- Also changed save for muutospyynto to return whole object instead of
returning only uuid.
=> CSCOIVA-714 Fixed attachment updating problems.

oiva-core/src/main/java/fi/minedu/oiva/backend/security/OivaUserDetailsService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/security/OpintopolkuCasWebSecurityAdapter.java, oiva-core/src/main/java/fi/minedu/oiva/backend/security/annotations/OivaAccess.java, oiva-core/src/main/scala/fi/minedu/oiva/backend/entity/opintopolku/KayttajaKayttooikeus.scala, oiva-core/src/test/resources/kayttajakayttooikeus.json, oiva-core/src/test/scala/fi/minedu/oiva/backend/service/OpintopolkuServiceSpec.scala
- If user has more than one organisation with oiva permissions the
first organisation is picked by backend.
=> CSCOIVA-728 Fixed user role and organisation bug.

README.md
Ensimmäinen versio uudistetusta README:sta. Työ on vielä kesken, koska kaikkea tarvittavaa tietämystä ei ole tällä hetkellä käytettävissä. Tässä on kuitenkin suunta, johon voidaan mahdollisesti uudistamisen kanssa edetä jatkossa.
=> Cscoiva 694

yva-backend/src/main/java/fi/minedu/oiva/backend/yva/web/controller/KujaPebbleController.java
- To see all user must be logged in as 'ESITTELIJA' role.
=> CSCKUJA-96 Fixed pebble lupa listing.

pom.xml, yva-backend/src/main/resources/db/migration/V5.3__Lukio_lupa_migration.sql
- Fixed multiple scala versions warning from maven build.
=> CSCKUJA-11 Added new lukio template migrations.

oiva-core-model/pom.xml, oiva-core-model/src/main/scala/fi/minedu/oiva/backend/model/entity/opintopolku/Organisaatio.scala, oiva-core/src/main/java/fi/minedu/oiva/backend/core/config/DatabasesConfig.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/OrganisaatioService.java, oiva-core/src/main/scala/fi/minedu/oiva/backend/core/service/OpintopolkuService.scala
- Configure flyway to accept migrations out of order.
=> CSCKUJA-155 Added muut kunnat for organisation.

oiva-core-model/src/main/scala/fi/minedu/oiva/backend/model/entity/oiva/Maarays.scala, oiva-core/src/main/java/fi/minedu/oiva/backend/core/extension/MaaraysListFilter.java
- Meta filter can be used as json key value filter.
=> CSCKUJA-158 Added meta filter for maaraysList.

oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/MuutospyyntoService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/web/controller/MuutospyyntoController.java, oiva-core/src/test/java/fi/minedu/oiva/backend/core/web/controller/BaseLiiteControllerIT.java, oiva-core/src/test/java/fi/minedu/oiva/backend/core/web/controller/BaseMuutospyyntoControllerIT.java, oiva-core/src/test/resources/sql/liite_data.sql, oiva-core/src/test/resources/sql/muutos_data.sql, oiva-core/src/test/resources/sql/muutos_liite_data.sql, oiva-core/src/test/resources/sql/muutospyynto_data.sql, oiva-core/src/test/resources/sql/muutospyynto_liite_data.sql, oiva-core/src/test/resources/sql/truncate.sql
- Api will return list of all liite objects tide to muutospyynto.
=> CSCKUJA-171 Added muutospyynto liite api call.

oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/KoodistoService.java
- Refactored/formated KoodistoService
=> CSCOIVA-581 Updated osaamisala koodis.

oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/FileStorageService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/MuutospyyntoService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/web/controller/MuutospyyntoController.java
Introducing new way in MuutospyyntoService to handle state (Tila) transitions.
Added and using new functionality to write out PDF files for Muutoshakemus into the server file storage path.
=> Cscoiva 1015

docker-compose.yml, nginx/yva-nginx.conf, oiva-docker.sh
- Now both oiva and kuja backends can be run simultaneously.
=> CSCKUJA-205 Added nginx for kuja and proper port mappings.

oiva-core-model/src/main/java/fi/minedu/oiva/backend/model/entity/json/TranslatedStringSerializer.java, oiva-core-model/src/main/java/fi/minedu/oiva/backend/model/util/ControllerUtil.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/config/RedisConfig.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/LupaService.java
- Fixed cache configs to use jackson serialization instead of default.
=> CSCOIVA-1134 Added cache for LupaService getByYtunnus method.

yva-backend/src/main/resources/db/migration/V9.8__HAMK_Akatemia_Oy.sql
- Hämeen liitto lupa cancellation.
=> CSCKUJA-327 HAMK Akatemia Oy lupa.

oiva-core-model/src/main/generated/jooq/fi/minedu/oiva/backend/model/jooq/Keys.java, oiva-core-model/src/main/generated/jooq/fi/minedu/oiva/backend/model/jooq/tables/Lupa.java
- These changes has been missing merge from hotfix branch.
=> CSCOIVA-1132 Removed diaarinumero unique key from lupa model.

amos-model/src/main/resources/db/migration/V12.2__Set_missing_historia_to_lupa.sql
Set references from lupahistoria to lupa where filename is in diaarinumero form.
=> CSCOIVA-1182 Set missing references from historia to lupa

README.md, oiva-db.sh, pom.xml
Counterpart in deployment repository https://github.com/CSCfi/oiva-deployment/pull/53
=> Updated db script

oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/LupaService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/MaaraysService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/web/controller/LupaController.java
- Default behaviour is using database koodisto version information but if set as 'false' the newest koodisto version is fetched.
=> CSCOIVA-940 Added koodistoversion overriding flag to api.

README.md, oiva-core-model/src/main/generated/jooq/fi/minedu/oiva/backend/model/jooq/tables/Lupa.java, oiva-core-model/src/main/generated/jooq/fi/minedu/oiva/backend/model/jooq/tables/pojos/Lupa.java, oiva-core-model/src/main/generated/jooq/fi/minedu/oiva/backend/model/jooq/tables/records/LupaRecord.java, oiva-db.sh
Fixed and reordered database initialization script, reflected changes in README.
Reverted mistakenly wrong field ordering in generated classes.
=> Database fixes

oiva-core-model/src/main/scala/fi/minedu/oiva/backend/model/entity/oiva/Muutospyynto.scala, oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/LiiteService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/MuutospyyntoService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/web/controller/MuutospyyntoController.java
Päätöskirje liitteen voi liittää ei-päätettyyn muutospyyntöön.
Muutospyynnön päättäminen liittää päätöskirje liitteen uuteen lupaan.
=> Cscoiva 1440

oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/MuutospyyntoService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/PrinceXMLService.java, oiva-core/src/test/java/fi/minedu/oiva/backend/core/web/controller/BaseMuutospyyntoControllerIT.java
- Set diaarinumero same as asianumero.
- Fixed integration tests.
=> CSCOIVA-1476 Removed paatoskirje from lupa pdf.

oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/LupaService.java
- Only lupa with tila "VALMIS" is taken account.
=> CSCOIVA-1556 Fixed csv report bug.

amos-backend/src/main/resources/db/migration/V17.6__Axxell_missing_maarays.sql, oiva-core/src/main/java/fi/minedu/oiva/backend/core/extension/MaaraysTransformerFilter.java
- Fixed tutkintokieli pebble filter bug when maarays has osaamisala and kieli alimaarays.
=> CSCOIVA-1574 Added missing tutkintokieli for Axxell

oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/MuutospyyntoService.java, oiva-core/src/test/java/fi/minedu/oiva/backend/core/service/MuutospyyntoServiceTest.java
- Force updater information to null when muutospyynto is created.
- Keep creator information intact when updating muutospyynto.
=> CSCOIVA-1656 Added diaarinumero saving to muutopyynto.

amos-backend/src/main/resources/db/migration/V21.2__Ending_lupa_for_Kaustisen_Evankelisen_Opiston_Kannatusyhdistys_ry.sql, amos-backend/src/main/resources/db/migration/V21.3__Ending_lupa_for_Vasa_stad.sql
- Fixed previous vst lupa ending migrations with koulutustyyppi and oppilaitostyyppi.
=> CSCOIVA-1620 Ending Vasa stad lupa.

oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/ExportService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/KohdeService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/web/controller/ExportController.java
- These api calls are only for ammatillinen lupa.
=> CSCOIVA-1733 Fixed koulutusluvat and koulutustarjonta export apis.

oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/ExportService.java, oiva-core/src/main/java/fi/minedu/oiva/backend/core/service/LupaService.java
- Asiatyyppi 'PERUUTETTU' is filtered.
=> CSCOIVA-1962 Fixed koulutusluvat and jarjestamisluvat query filtering.
